FROM node:alpine AS development

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./
COPY nest-cli.json ./

RUN npm install

COPY apps/auth ./apps/auth
COPY libs ./libs

RUN cd apps/auth && npm install

RUN npm run build auth

FROM node:alpine AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install --omit=dev

COPY apps/auth/package.json ./auth-packages/package.json

RUN npm install ./auth-packages --prefix . --omit=dev

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/apps/auth/main"]